# Welcome to Jupyter!

## Joining (Merging) DataFrames

In [2]:
import pandas as pd

In [ ]:
movies = pd.read_csv('movie_data.csv')
movies.head()

In [ ]:
movies.shape

In [ ]:
movies.movie_id.nunique()

In [ ]:
ratings = pd.read_csv(rating_data.csv'')
ratings.head()

In [ ]:
ratings.shape

In [ ]:
ratings.movie_id.nunique()

In [ ]:
ratings.loc[ratings.movie_id == 1, :].head()

## Merging Movies and Ratings

In [ ]:
movies.columns

In [ ]:
ratings.columns

In [ ]:
movie_ratings = pd.merge(movies, ratings)
movie_ratings.columns

In [ ]:
movie_ratings.head()

In [ ]:
movie_ratings.shape

## What if the columns you want to join on don't have the same name?

In [ ]:
movies.columns = ['m_id', 'title']
movies.columns

In [ ]:
Index(['m_id', 'title'], dtype='object')

In [ ]:
ratings.columns

In [ ]:
pd.merge(movies, ratings, left_on='m_id', right_on='movie_id').head()

In [ ]:
movies = movies.set_index('m_id')
movies.head()

In [ ]:
pd.merge(movies, ratings, left_index=True, right_on='movie_id').head()

In [ ]:
ratings = ratings.set_index('movie_id')
ratings.head()

In [ ]:
pd.merge(movies, ratings, left_index=True, right_index=True).head()

## Four Types of Joins

In [3]:
A = pd.DataFrame({'color': ['green', 'yellow', 'red'], 'num':[1, 2, 3]})
A

    color  num
0   green    1
1  yellow    2
2     red    3

In [4]:
B = pd.DataFrame({'color': ['green', 'yellow', 'pink'], 'size':['S', 'M', 'L']})
B

    color size
0   green    S
1  yellow    M
2    pink    L

## Inner join

In [6]:
pd.merge(A, B, how='inner')

    color  num size
0   green    1    S
1  yellow    2    M

## Outer join

In [7]:
pd.merge(A, B, how='outer')

    color  num size
0   green  1.0    S
1  yellow  2.0    M
2     red  3.0  NaN
3    pink  NaN    L

## Left join

In [8]:
pd.merge(A, B, how='left')

    color  num size
0   green    1    S
1  yellow    2    M
2     red    3  NaN

## Right join

In [9]:
pd.merge(A, B, how='right')

    color  num size
0   green  1.0    S
1  yellow  2.0    M
2    pink  NaN    L

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook